global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
  
  - job_name: 'service-one'
    static_configs:
      - targets: ['service-one:8001']
  
  - job_name: 'service-two'
    static_configs:
      - targets: ['service-two:8002']
